### ISSUE TITLE
Clicking 'X' on a tag when allowDelete is set to 'false' still removes tag

### ISSUE THREAD

**Issue by hartez** [webworka/Tagedit#16]
Setting the 'allowDelete' option to false doesn't prevent the user from clicking the 'X' button on a tag and removing the tag.

**Comment by webworka** [comment]
Hi hartez,

this is some kind of misunderstanding. The option "allowdelete" is there to not allow the deletion from database. 
The "x" does only mean to remove the Tag from the List, not from the database.

Regards,

Oliver

**Comment by hartez** [comment]
Is there any way to make the list read-only? I would like to display the tags without allowing the user to add or remove from the list.

**Comment by webworka** [comment]
In that case there is not Javascript necessary, isn't it? So you could just place a ul with the class 'tagedit-list' and place some list elements inside.
