### ISSUE TITLE
Does not work on single input field

### ISSUE THREAD

**Issue by tejinderss** [webworka/Tagedit#18]
I have a single input field and i want to apply tagedit to it so that i can pass the local source data to it and it should return comma separated tags to the backend. For example:

```
My input field looks like this:

<input type="text" name="tags" id="id_tags" />

var localJSON = [
        { "label": "Hazel Grouse", "value": "Hazel Grouse" },
        { "label": "Common Quail",  "value": "Common Quail" },
        { "label": "Greylag Goose", "value": "Greylag Goose" }
    ];
```

  $('#id_tags').tagedit({
      autocompleteOptions: {
        source: localJSON,
        },
  });

If i dont rename my input to "test[]" it gives error saying dow does not match the regular expression. And if i rename my input field to test[3-a] then the returned field becomes test[] = values, while i don't want the tagedit to rename my input field, because the backend does not recognize the renamed field. And there is no indication in documentation what does this figures in [] denote? I just want to apply tags to input field so that it should return the comma separated string, like if i select 2 tags "Hazel Grouse" and "Common Quail", it should pass to input id test as "Hazel Grouse, Common Quail". Is it possible. Please guide.

**Comment by tejinderss** [comment]
Another issue related to this, if i use empty list tags[], allowEdit: false, allowAdd: false, dont work. I just cannot select any tag using these 2 options. What i want to accomplish is to disable adding the new tags to the list so that the user is restricted to the tags which are provided with the autocomplete.

**Comment by webworka** [comment]
Answer to the first issue: (I've put the second to a new Issue #19)

The usage that you described is another approach. This plugin was created to provide a list of input fields. Therefore there is a naming convention that says, It has to be "[]" at the end of the name.
In Backends based on php, the list will be available as array in the request. It's not possible to provide a comma separated list with this.

I can not reproduce the error you've seen when renaming the input field to test[]. An example with local data iust also available on http://tagedit.webwork-albrecht.de/playground.html ("Use local source for autocomplete list")
