### ISSUE TITLE
Existing Entries Aren't Added When Pressing Enter

### ISSUE THREAD

**Issue by mmezzacca** [webworka/Tagedit#2]
When typing a tag and pressing enter (when the entry exists in the autocomplete list), it does not add it to the list.  It just disappears. Even if you highlight the entry in the Autocomplete area and hit enter, it isn't added.

**Comment by webworka** [comment]
Thanks, I have a look on this after my vacation, next week.

**Comment by mmezzacca** [comment]
Great, I'll check back then.

**Comment by mmezzacca** [comment]
Just a quick note, my issue was encountered when using FireFox.  I tried it in IE8 and highlighting the tag in the autocomplete drop down and pressing enter works.  Still doesn't work if you just enter an existing tag and hit enter.

**Comment by webworka** [comment]
There is a bugfix available in v1.1.0 Thanks for the hint.

**Comment by mmezzacca** [comment]
Sweet thanks for the quick fix.  I'll take a look.
