### ISSUE TITLE
Input name regex unnecessarily restrictive

### ISSUE THREAD

**Issue by jdart** [webworka/Tagedit#4]
The below regex would cause problems for input names generated by web frameworks like Symfony and Rails. Often you'll see a name with more than one use of square brackets.

``` javascript
var baseNameRegexp = new RegExp("^([a-z0-9_]*)\\[([0-9]*?("+options.deletedPostfix+"|"+options.addedPostfix+")?)?\]$", "i");
```

How about changing it to something like the below?

``` javascript
var baseNameRegexp = new RegExp("^(.*)\\[([0-9]*?("+options.deletedPostfix+"|"+options.addedPostfix+")?)?\]$", "i");      
```

**Comment by webworka** [comment]
Hi,
if you want to have an empty list you can put an empty input with empty brackets: name="somename[]". I do it this way in all my projects.

Nevertheless the idea is interesting to start optionally with an empty list. I'll check this.

Oliver

**Comment by webworka** [comment]
Good idea. I'll check this next week.

**Comment by webworka** [comment]
I'll change the regex. Thanks again.
