### ISSUE TITLE
Feature Request: Case Sensitive Option On/Off

### ISSUE THREAD

**Issue by mmezzacca** [webworka/Tagedit#8]
A case in-sensitive option for autocomplete (match existing entries regardless of case).  Currently you can have any number of tags that are the same eg. "tennis", "TENNIS" and "Tennis".

Not sure if this was fixed in the latest release but I didn't see it.

**Comment by webworka** [comment]
Do you mean for the autocompletion list or for the function that checks if an entry is a new one?

**Comment by mmezzacca** [comment]
Hmm, I guess for the function that checks if it is a new entry...  For example, if "Tennis" is in the auto complete list and already in the current list, if I type "tennis" the autocomplete works by showing "Tennis" but if I hit enter it thinks that "tennis" is a new entry.  And so both "Tennis" and "tennis" appear on the list.  Does that make sense?

**Comment by webworka** [comment]
No, this does not make sense in most cases. I'll add an option for this. Default behaviour should be in-sensitive in my opinion.

**Comment by mmezzacca** [comment]
Ok, thanks.  To clarify, currently it operates as case sensitive?

**Comment by webworka** [comment]
Yes. That is the reason why you can put "merlin" in the first Input on the example page. "Merlin" does not work, as expected.

**Comment by mmezzacca** [comment]
So are you saying you should change this default behavior to in-sensitive?

**Comment by webworka** [comment]
Yes. in my opinion the in-sensitive behaviour is the one that is mostly needed. Don't you think?

**Comment by mmezzacca** [comment]
Yes, I agree.

**Comment by webworka** [comment]
Option added in version 1.2.0
